services:
  db:
    image: postgres:15-alpine
    container_name: pg-quotes
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quotes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d quotes" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quotes-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/quotes?schema=public
    depends_on:
      db:
        condition: service_healthy

  test:
    profiles:
      - test
    build:
      context: .
      dockerfile: Dockerfile
      target: tester
    container_name: quotes-api-test
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/quotes?schema=public
    depends_on:
      db:
        condition: service_healthy


volumes:
  postgres_data:
